### ISSUE TITLE
NSFW Cog doesnt load 

### ISSUE THREAD

**Issue by minenightowl** [PredaaA/predacogs#27]
`[2020-06-11 01:29:04] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "c:\users\kimch\redenv\lib\site-packages\redbot\core\core_commands.py", line 118, in _load
    await bot.load_extension(spec)
  File "c:\users\kimch\redenv\lib\site-packages\redbot\core\bot.py", line 907, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kimch\Desktop\REDV3\cogs\CogManager\cogs\nsfw\__init__.py", line 2, in <module>
    from .nsfw import NSFW
  File "C:\Users\kimch\Desktop\REDV3\cogs\CogManager\cogs\nsfw\nsfw.py", line 15, in <module>
    from .rule34 import Rule34
  File "C:\Users\kimch\Desktop\REDV3\cogs\CogManager\cogs\nsfw\rule34.py", line 4, in <module>
    from .api_wrapper import APIWrapper
  File "C:\Users\kimch\Desktop\REDV3\cogs\CogManager\cogs\nsfw\api_wrapper.py", line 3, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'
[2020-06-11 01:31:34] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "c:\users\kimch\redenv\lib\site-packages\redbot\core\core_commands.py", line 117, in _load
    self._cleanup_and_refresh_modules(spec.name)
  File "c:\users\kimch\redenv\lib\site-packages\redbot\core\core_commands.py", line 177, in _cleanup_and_refresh_modules
    importlib._bootstrap._exec(lib.__spec__, lib)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: errors.py`

![image](https://user-images.githubusercontent.com/29973351/84349013-6b276c80-ab84-11ea-9375-f50d27b3ddb5.png)

**Comment by PredaaA** [comment]
Discussed and fixed on my server.
