### ISSUE TITLE
Cannot load RandImages cog

### ISSUE THREAD

**Issue by WhynautTV** [PredaaA/predacogs#44]
`[2020-09-18 06:26:03] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "c:\users\cameron\redenv\lib\site-packages\discord\ext\commands\cog.py", line 384, in _inject
    bot.add_command(command)
  File "c:\users\cameron\redenv\lib\site-packages\redbot\core\bot.py", line 1260, in add_command
    super().add_command(command)
  File "c:\users\cameron\redenv\lib\site-packages\discord\ext\commands\core.py", line 1131, in add_command
    raise CommandRegistrationError(command.name)
discord.ext.commands.errors.CommandRegistrationError: The command meme is already an existing command or alias.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cameron\redenv\lib\site-packages\redbot\core\core_commands.py", line 170, in _load
    await bot.load_extension(spec)
  File "c:\users\cameron\redenv\lib\site-packages\redbot\core\bot.py", line 1104, in load_extension
    await lib.setup(self)
  File "C:\Users\Cameron\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\danny\cogs\CogManager\cogs\randimages\__init__.py", line 11, in setup
    bot.add_cog(cog)
  File "c:\users\cameron\redenv\lib\site-packages\redbot\core\bot.py", line 1239, in add_cog
    super().add_cog(cog)
  File "c:\users\cameron\redenv\lib\site-packages\discord\ext\commands\bot.py", line 508, in add_cog
    cog = cog._inject(self)
  File "c:\users\cameron\redenv\lib\site-packages\discord\ext\commands\cog.py", line 388, in _inject
    bot.remove_command(to_undo)
  File "c:\users\cameron\redenv\lib\site-packages\redbot\core\bot.py", line 1273, in remove_command
    command = self.get_command(name)
  File "c:\users\cameron\redenv\lib\site-packages\redbot\core\bot.py", line 270, in get_command
    com = super().get_command(name)
  File "c:\users\cameron\redenv\lib\site-packages\discord\ext\commands\core.py", line 1204, in get_command
    if ' ' not in name:
TypeError: argument of type 'Command' is not iterable`

**Comment by PredaaA** [comment]
> `discord.ext.commands.errors.CommandRegistrationError: The command meme is already an existing command or alias.`
You already have a `meme` command on another cog on your bot. You can find it by using `[p]findcog meme`, then unload that cog and you'll be able to load this one.

**Comment by WhynautTV** [comment]
Thank you, feels like read everything but that line.
